### ISSUE TITLE
compiled library as sqlite3 are not available when loading inside the commands

### ISSUE THREAD

**Issue by FabienArcellier** [FabienArcellier/alfred-cli#29]
This command throws an exception. `ModuleNotFoundError: No module named 'sqlite3'`

```python
@alfred.command("test")
def test():
    import sqlite3
    print(sqlite3.sqlite_version)
```
Libraries like `sqlite3` and `optparse` cannot be imported at runtime but `math` library can be imported

This code, however, works.

```python
import sqlite3

@alfred.command("test")
def test():
    print(sqlite3.sqlite_version)
```

## work around

The management of the path of the libraries is wrong in the code of alfred. Some paths are erased when invoking a command. A work around is to manually add the missing paths in the python_path_extends parameter.

```toml
[alfred.project]
python_path_extends = ["/usr/lib/python3.10", '/usr/lib/python3.10/lib-dynload']
```

These 2 paths are visible in the interpreter info

```python
import sys
print(sys.path)
```
